# generated by datamodel-codegen:
#   filename:  schema.json
#   timestamp: 2025-10-25T07:27:04+00:00

from __future__ import annotations

from datetime import date
from typing import List, Optional

from pydantic import BaseModel, Extra, Field


class UebernachtungenItem(BaseModel):
    datum: Optional[date] = Field(None, description='Das Datum der Übernachtung')
    preis: Optional[float] = Field(
        None, description='Der Preis für die Übernachtung ohne Frühstück'
    )


class Zahlungsdetails(BaseModel):
    zahlungsmethode: Optional[str] = Field(
        None, description='Die verwendete Zahlungsmethode'
    )
    betrag: Optional[float] = Field(None, description='Der bezahlte Gesamtbetrag')


class Steuern(BaseModel):
    nettoBetrag: Optional[float] = Field(
        None, description='Der Nettobetrag der Rechnung'
    )
    mehrwertsteuerSatz: Optional[float] = Field(
        None, description='Der angewendete Mehrwertsteuersatz in Prozent'
    )
    mehrwertsteuerBetrag: Optional[float] = Field(
        None, description='Der Betrag der Mehrwertsteuer'
    )
    bruttoBetrag: Optional[float] = Field(
        None, description='Der Bruttobetrag der Rechnung'
    )


class HotelInformationen(BaseModel):
    name: Optional[str] = Field(None, description='Der Name des Hotels')
    adresse: Optional[str] = Field(None, description='Die Adresse des Hotels')
    telefon: Optional[str] = Field(None, description='Die Telefonnummer des Hotels')
    email: Optional[str] = Field(None, description='Die E-Mail-Adresse des Hotels')
    website: Optional[str] = Field(None, description='Die Website des Hotels')
    steuernummer: Optional[str] = Field(None, description='Die Steuernummer des Hotels')


class Model(BaseModel):
    class Config:
        extra = Extra.allow

    rechnungsnummer: Optional[str] = Field(None, description='Die Nummer der Rechnung')
    rechnungsdatum: Optional[date] = Field(
        None, description='Das Datum der Rechnungsstellung'
    )
    zimmer: Optional[str] = Field(None, description='Die Zimmernummer des Gastes')
    anreise: Optional[date] = Field(None, description='Das Anreisedatum des Gastes')
    abreise: Optional[date] = Field(None, description='Das Abreisedatum des Gastes')
    benutzerID: Optional[str] = Field(None, description='Die Benutzer-ID des Gastes')
    gastname: Optional[str] = Field(None, description='Der Name des Gastes')
    uebernachtungen: Optional[List[UebernachtungenItem]] = Field(
        None, description='Liste der Übernachtungen mit Datum und Preis'
    )
    zahlungsdetails: Optional[Zahlungsdetails] = Field(
        None, description='Details zur Zahlung'
    )
    steuern: Optional[Steuern] = Field(None, description='Steuerdetails der Rechnung')
    hotelInformationen: Optional[HotelInformationen] = Field(
        None, description='Informationen über das Hotel'
    )
