# generated by datamodel-codegen:
#   filename:  schema.json
#   timestamp: 2025-10-25T08:50:29+00:00

# from datetime import date as date_aliased
# from datetime import time as time_aliased
from typing import List, Literal, Optional
from pydantic import BaseModel, Field

from ._types import Confidence, Datetime


class Store(BaseModel):
  name: Optional[str] = Field(None, description='Name of the store')
  address: Optional[str] = Field(None, description='Address of the store')
  phone: Optional[str] = Field(None, description='Phone number of the store')
  taxId: Optional[str] = Field(
    None, description='Tax identification number of the store'
  )
  confidence: Confidence


class Receipt(BaseModel):
  number: Optional[str] = Field(None, description='Receipt number')
  date: Optional[Datetime] = Field(None, description='Date and time of purchase')
  confidence: Confidence


class Item(BaseModel):
  code: Optional[str] = Field(None, description='Product code')
  description: str = Field(description='Product description')
  price: float = Field(description='Price of the item')
  currency: str = Field(description='Currency of `price`.')
  confidence: Confidence


class Payment(BaseModel):
  method: Optional[str] = Field(None, description='Payment method used')
  cardNumber: Optional[str] = Field(
    None, description='Partial card number used for payment'
  )
  authorizationNumber: Optional[str] = Field(
    None, description='Authorization number for the payment'
  )
  confidence: Confidence


class Vat(BaseModel):
  rate: Optional[float] = Field(None, description='VAT rate applied')
  amount: float = Field(description='VAT amount')
  currency: str = Field(description='Currency of `amount`.')
  confidence: Confidence


class Totals(BaseModel):
  gross: float = Field(description='Gross total amount')
  net: Optional[float] = Field(None, description='Net total amount')
  vat: Optional[Vat] = Field(None)
  currency: str = Field(description='Currency of `gross` and `net`.')
  confidence: Confidence


class ShopModel(BaseModel):
  # class Config:
  #   extra = Extra.allow
  kind: Literal['shop']
  store: Optional[Store] = Field(None)
  receipt: Optional[Receipt] = Field(None)
  items: List[Item] = Field(description='List of purchased items', default_factory=list)
  payment: Optional[Payment] = Field(None)
  totals: Optional[Totals] = Field(None)
  confidence: Confidence
  free_text: str = Field(description='A free text comment. Add any other relevant information not part of the schema but important for the user here.')
